In [1]:
import pandas as pd
import numpy as np


# Assuming you have a DataFrame named 'data' with a column 'Label'
# Replace this with your actual data loading code if needed
data = pd.read_csv('data_stemming.csv')

In [2]:
Label = data['Label']
clean_text=data['Teks']


In [3]:
clean_text

0     sekjen partai gerindra ahmad muzani singgung c...
1     sekjen partai gerindra ahmad muzani singgung c...
2     calon wakil presiden bacawapres koalisi ubah m...
3     polres indramayu terjun pondok pesantren ponpe...
4     menteri agama jabat ketua tum gp ansor yaqut c...
                            ...                        
85    nama ragil kembar dwi suryo akrab sapa immanue...
86    pusat hibur keluarga timezone umum luas venuen...
87    main musik sangka nyanyi wanita talenta angie ...
88    vokalis band wali farhan zainal muttaqin kenal...
89    lalisa manoban kenal nama lisa blackpink sorot...
Name: Teks, Length: 90, dtype: object

In [4]:
import re
import nltk
from nltk.tokenize import word_tokenize
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [5]:
for i in clean_text:
    print(i)

sekjen partai gerindra ahmad muzani singgung cawapres gibran rakabuming pimpin pks nilai anak muda milik hak kesempatananak muda hak anak muda sempat bagus nggak anak muda ketua dpp pks mardani ali sera wartawan jumat mardani proses barus proses etika scroll to continue with content syarat proses proses etika ujarnyamardani dukung anak muda kualitas sebut pks masalah anak muda pimpin pilih rakyatkita dukung anak muda kualitas integritas pilih rakyat mesti ujarnyamuzani sindir duet capres cawapres prabowo subianto gibran rakabuming raka muzani sebab suka pasang iniitu orang suka pasang prabowo gibran orang situasi milu sepakat mas gibran cawapres koalisi indonesia maju sambut indonesia emas muzani hadir konsolidasi ribu kader kabupaten tegal kota tegal kutip jumat muzani sebut khawatir peran anak muda signifikan milu sebut gibran wakil anak muda siap indonesia emasagar usia negara indonesia gibran wakil anak muda siap indonesia emas generasi muda siap pimpin rela muzaniwakil ketua tkn p

In [6]:
word_token=[word_tokenize(i) for i in clean_text]

In [7]:
word_token

[['sekjen',
  'partai',
  'gerindra',
  'ahmad',
  'muzani',
  'singgung',
  'cawapres',
  'gibran',
  'rakabuming',
  'pimpin',
  'pks',
  'nilai',
  'anak',
  'muda',
  'milik',
  'hak',
  'kesempatananak',
  'muda',
  'hak',
  'anak',
  'muda',
  'sempat',
  'bagus',
  'nggak',
  'anak',
  'muda',
  'ketua',
  'dpp',
  'pks',
  'mardani',
  'ali',
  'sera',
  'wartawan',
  'jumat',
  'mardani',
  'proses',
  'barus',
  'proses',
  'etika',
  'scroll',
  'to',
  'continue',
  'with',
  'content',
  'syarat',
  'proses',
  'proses',
  'etika',
  'ujarnyamardani',
  'dukung',
  'anak',
  'muda',
  'kualitas',
  'sebut',
  'pks',
  'masalah',
  'anak',
  'muda',
  'pimpin',
  'pilih',
  'rakyatkita',
  'dukung',
  'anak',
  'muda',
  'kualitas',
  'integritas',
  'pilih',
  'rakyat',
  'mesti',
  'ujarnyamuzani',
  'sindir',
  'duet',
  'capres',
  'cawapres',
  'prabowo',
  'subianto',
  'gibran',
  'rakabuming',
  'raka',
  'muzani',
  'sebab',
  'suka',
  'pasang',
  'iniitu',
  'ora

In [8]:
data_enc=[]
for i in word_token:
    data_enc=data_enc+i

In [9]:
data_enc

['sekjen',
 'partai',
 'gerindra',
 'ahmad',
 'muzani',
 'singgung',
 'cawapres',
 'gibran',
 'rakabuming',
 'pimpin',
 'pks',
 'nilai',
 'anak',
 'muda',
 'milik',
 'hak',
 'kesempatananak',
 'muda',
 'hak',
 'anak',
 'muda',
 'sempat',
 'bagus',
 'nggak',
 'anak',
 'muda',
 'ketua',
 'dpp',
 'pks',
 'mardani',
 'ali',
 'sera',
 'wartawan',
 'jumat',
 'mardani',
 'proses',
 'barus',
 'proses',
 'etika',
 'scroll',
 'to',
 'continue',
 'with',
 'content',
 'syarat',
 'proses',
 'proses',
 'etika',
 'ujarnyamardani',
 'dukung',
 'anak',
 'muda',
 'kualitas',
 'sebut',
 'pks',
 'masalah',
 'anak',
 'muda',
 'pimpin',
 'pilih',
 'rakyatkita',
 'dukung',
 'anak',
 'muda',
 'kualitas',
 'integritas',
 'pilih',
 'rakyat',
 'mesti',
 'ujarnyamuzani',
 'sindir',
 'duet',
 'capres',
 'cawapres',
 'prabowo',
 'subianto',
 'gibran',
 'rakabuming',
 'raka',
 'muzani',
 'sebab',
 'suka',
 'pasang',
 'iniitu',
 'orang',
 'suka',
 'pasang',
 'prabowo',
 'gibran',
 'orang',
 'situasi',
 'milu',
 'sepa

**1. One Hot Encoding**

In [10]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(data_enc)
print(integer_encoded)
# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)
# invert first example
inverted = label_encoder.inverse_transform([argmax(onehot_encoded[0, :])])
print(inverted)

[3041 2476 1092 ...  421  717   48]


c:\Users\Lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
['sekjen']


In [11]:
onehot_encoded[0]

array([0., 0., 0., ..., 0., 0., 0.])

**CountVectorizer**

In [94]:
from sklearn.feature_extraction.text import CountVectorizer

In [95]:
#tokenizer dilakukan pada proses ini, sehingga inputnya adalah data setelah cleansing
#bigram
vectorizer = CountVectorizer(ngram_range=(2, 2)) #n_gram
X = vectorizer.fit_transform(clean_text)
CVec=pd.DataFrame(X.toarray(),columns=vectorizer.get_feature_names_out())
CVec.head()

ab solissa  abad abad  abad integral  abad turun  abar anggota  \
0           0          0              0           0             0   
1           0          0              0           0             0   
2           0          0              0           0             0   
3           0          0              0           0             0   
4           0          0              0           0             0   

   abdi masyarakat  abdi rakyat  abdi sejahtera  abdurrohim dia  \
0                0            0               0               0   
1                0            0               0               0   
2                0            0               0               0   
3                0            0               0               0   
4                0            0               0               0   

   abdurrohim turnamen  ...  zaitun telur  zealand menandatangani  \
0                    0  ...             0                       0   
1                    0  ...             0                       0   
2                    0  ...             0                       0   
3                    0  ...             0                       0   
4                    0  ...             0                       0   

   zelena piawai  zhang bonus  zhang telepon  zhuhai china  zumba lucky  \
0              0            0              0             0            0   
1              0            0              0             0            0   
2              0            0              0             0            0   
3              0            0              0             0            0   
4              0            0              0             0            0   

   zx liput  zx moge  zx performa  
0         0        0            0  
1         0        0            0  
2         0        0            0  
3         0        0            0  
4         0        0            0  

[5 rows x 12497 columns]

In [96]:
vectorizer = CountVectorizer(ngram_range=(1, 1))
X = vectorizer.fit_transform(clean_text)
CVec=pd.DataFrame(X.toarray(),columns=vectorizer.get_feature_names_out())
CVec.head()

#jika lebih data yang panjang lebih dari 1 aja, pasti lebih panjang feature kita sehingga banyak sparce / 0.add()
#

ab  abad  abar  abdi  abdurrohim  abis  abs  absolut  absorbersroda  ac  \
0   0     0     0     0           0     0    0        0              0   0   
1   0     0     0     0           0     0    0        0              0   0   
2   0     0     0     0           0     0    0        0              0   0   
3   0     0     0     0           0     0    0        0              0   0   
4   0     0     0     0           0     0    0        0              0   0   

   ...  yuto  yves  zainal  zaitun  zealand  zelena  zhang  zhuhai  zumba  zx  
0  ...     0     0       0       0        0       0      0       0      0   0  
1  ...     0     0       0       0        0       0      0       0      0   0  
2  ...     0     0       0       0        0       0      0       0      0   0  
3  ...     0     0       0       0        0       0      0       0      0   0  
4  ...     0     0       0       0        0       0      0       0      0   0  

[5 rows x 3823 columns]

In [97]:
from sklearn.feature_extraction.text import CountVectorizer

# Assuming clean_text is a list or Series containing the preprocessed text data

# Create a CountVectorizer with 1-grams and 2-grams
vectorizer = CountVectorizer(stop_words="english", ngram_range=(1, 2))

# Fit and transform the text data
X = vectorizer.fit_transform(clean_text)

# Convert the result to a DataFrame
CVec = pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names_out())

# Display the first few rows of the DataFrame
CVec.head()


ab  ab solissa  abad  abad abad  abad integral  abad turun  abar  \
0   0           0     0          0              0           0     0   
1   0           0     0          0              0           0     0   
2   0           0     0          0              0           0     0   
3   0           0     0          0              0           0     0   
4   0           0     0          0              0           0     0   

   abar anggota  abdi  abdi masyarakat  ...  zhang bonus  zhang telepon  \
0             0     0                0  ...            0              0   
1             0     0                0  ...            0              0   
2             0     0                0  ...            0              0   
3             0     0                0  ...            0              0   
4             0     0                0  ...            0              0   

   zhuhai  zhuhai china  zumba  zumba lucky  zx  zx liput  zx moge  \
0       0             0      0            0   0         0        0   
1       0             0      0            0   0         0        0   
2       0             0      0            0   0         0        0   
3       0             0      0            0   0         0        0   
4       0             0      0            0   0         0        0   

   zx performa  
0            0  
1            0  
2            0  
3            0  
4            0  

[5 rows x 16169 columns]

In [98]:
CVec.columns

Index(['ab', 'ab solissa', 'abad', 'abad abad', 'abad integral', 'abad turun',
       'abar', 'abar anggota', 'abdi', 'abdi masyarakat',
       ...
       'zhang bonus', 'zhang telepon', 'zhuhai', 'zhuhai china', 'zumba',
       'zumba lucky', 'zx', 'zx liput', 'zx moge', 'zx performa'],
      dtype='object', length=16169)

In [99]:
#from sklearn.feature_extraction.text import CountVectorizer

# Tokenization is done in this step, so the input is the data after cleansing
# 1-gram and 2-gram
vectorizer = CountVectorizer(ngram_range=(1, 2))
X = vectorizer.fit_transform(clean_text)

# Create a DataFrame to see the Count Vectorizer representation
feature_names = vectorizer.get_feature_names_out()
CVec = pd.DataFrame(X.toarray(), columns=feature_names)

CVec.head()


ab  ab solissa  abad  abad abad  abad integral  abad turun  abar  \
0   0           0     0          0              0           0     0   
1   0           0     0          0              0           0     0   
2   0           0     0          0              0           0     0   
3   0           0     0          0              0           0     0   
4   0           0     0          0              0           0     0   

   abar anggota  abdi  abdi masyarakat  ...  zhang bonus  zhang telepon  \
0             0     0                0  ...            0              0   
1             0     0                0  ...            0              0   
2             0     0                0  ...            0              0   
3             0     0                0  ...            0              0   
4             0     0                0  ...            0              0   

   zhuhai  zhuhai china  zumba  zumba lucky  zx  zx liput  zx moge  \
0       0             0      0            0   0         0        0   
1       0             0      0            0   0         0        0   
2       0             0      0            0   0         0        0   
3       0             0      0            0   0         0        0   
4       0             0      0            0   0         0        0   

   zx performa  
0            0  
1            0  
2            0  
3            0  
4            0  

[5 rows x 16320 columns]

**TF-IDF**

In [100]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Tokenization is done in this step, so the input is the data after cleansing
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(clean_text)

# Create a DataFrame to see the TF-IDF representation
feature_names = vectorizer.get_feature_names_out()
TFIDF = pd.DataFrame(X.toarray(), columns=feature_names)

TFIDF.head()


ab  abad  abar  abdi  abdurrohim  abis  abs  absolut  absorbersroda   ac  \
0  0.0   0.0   0.0   0.0         0.0   0.0  0.0      0.0            0.0  0.0   
1  0.0   0.0   0.0   0.0         0.0   0.0  0.0      0.0            0.0  0.0   
2  0.0   0.0   0.0   0.0         0.0   0.0  0.0      0.0            0.0  0.0   
3  0.0   0.0   0.0   0.0         0.0   0.0  0.0      0.0            0.0  0.0   
4  0.0   0.0   0.0   0.0         0.0   0.0  0.0      0.0            0.0  0.0   

   ...  yuto  yves  zainal  zaitun  zealand  zelena  zhang  zhuhai  zumba   zx  
0  ...   0.0   0.0     0.0     0.0      0.0     0.0    0.0     0.0    0.0  0.0  
1  ...   0.0   0.0     0.0     0.0      0.0     0.0    0.0     0.0    0.0  0.0  
2  ...   0.0   0.0     0.0     0.0      0.0     0.0    0.0     0.0    0.0  0.0  
3  ...   0.0   0.0     0.0     0.0      0.0     0.0    0.0     0.0    0.0  0.0  
4  ...   0.0   0.0     0.0     0.0      0.0     0.0    0.0     0.0    0.0  0.0  

[5 rows x 3823 columns]

In [14]:
X

<90x3823 sparse matrix of type '<class 'numpy.float64'>'
	with 9888 stored elements in Compressed Sparse Row format>

**Word2Vec - CBOW**

In [103]:
pip install gensim


Note: you may need to restart the kernel to use updated packages.


In [19]:
import gensim
from gensim.models import Word2Vec 

In [104]:
model_cbow = gensim.models.Word2Vec(word_token, min_count=3, vector_size=50, window=5, sg=0)


In [105]:
# Accessing the vocabulary
vocabulary_cbow = model_cbow.wv.key_to_index
print(vocabulary_cbow)

# Accessing word vectors
word_vectors = model_cbow.wv.key_to_index


{'indonesia': 0, 'prabowo': 1, 'gibran': 2, 'pilih': 3, 'entertainment': 4, 'blackpink': 5, 'yg': 6, 'masyarakat': 7, 'presiden': 8, 'milik': 9, 'milu': 10, 'olahraga': 11, 'orang': 12, 'to': 13, 'juta': 14, 'anak': 15, 'content': 16, 'scroll': 17, 'kontrak': 18, 'sebut': 19, 'calon': 20, 'sport': 21, 'rp': 22, 'partai': 23, 'salah': 24, 'dukung': 25, 'bisnis': 26, 'lisa': 27, 'korea': 28, 'jakarta': 29, 'raffi': 30, 'dunia': 31, 'muda': 32, 'motor': 33, 'hasil': 34, 'saham': 35, 'grup': 36, 'selatan': 37, 'lapor': 38, 'k': 39, 'temu': 40, 'jumat': 41, 'kali': 42, 'anggota': 43, 'tingkat': 44, 'saudi': 45, 'konser': 46, 'nagita': 47, 'pop': 48, 'politik': 49, 'kota': 50, 'turut': 51, 'usia': 52, 'media': 53, 'ketua': 54, 'nama': 55, 'pasang': 56, 'selenggara': 57, 'wakil': 58, 'subianto': 59, 'debut': 60, 'hadir': 61, 'negara': 62, 'main': 63, 'tim': 64, 'suara': 65, 'turun': 66, 'jalan': 67, 'harga': 68, 'lagu': 69, 'buka': 70, 'besar': 71, 'cawapres': 72, 'with': 73, 'latih': 74, 'co

In [22]:
print(model_cbow.wv.similarity('wakil','cawapres'))

0.9126168


In [23]:
similar_words = model_cbow.wv.most_similar("cawapres")
print(similar_words)

[('temu', 0.9645721316337585), ('jakarta', 0.9635567665100098), ('prabowo', 0.9630090594291687), ('masyarakat', 0.962014377117157), ('indonesia', 0.9611748456954956), ('saudi', 0.9610646367073059), ('sepak', 0.9608860015869141), ('dukung', 0.9590790867805481), ('jumat', 0.9581478834152222), ('debut', 0.9581243991851807)]


In [24]:
#get the vector
vectors_cbow = [model_cbow.wv.get_vector(word)for word in vocabulary_cbow]

In [25]:
vectors_cbow[0]

array([ 0.00149335, -0.03810238,  0.03522444,  0.01787957, -0.10737038,
       -0.13062492,  0.13326076,  0.19914691, -0.21299821, -0.03231747,
       -0.0069628 , -0.16315104, -0.04462728,  0.05667868, -0.1390621 ,
        0.05742735,  0.09621227, -0.05546005, -0.17659847, -0.13258159,
        0.03679877,  0.09523764,  0.14778353, -0.09073357,  0.07115384,
       -0.00305188, -0.08639593, -0.11023476, -0.15592206,  0.04786574,
        0.06311773,  0.01337255, -0.08711522,  0.00779307, -0.10525912,
        0.18863945,  0.02104534,  0.01085206,  0.04420107, -0.20089044,
        0.09486632, -0.04077755, -0.02676434,  0.03949385,  0.29624468,
        0.06344707, -0.02168897, -0.14146587,  0.07418174,  0.08709598],
      dtype=float32)

**Word2Vec - Skipgram**

In [53]:
model_skipgram = gensim.models.Word2Vec(word_token, min_count = 3,vector_size = 50, window = 5, sg=1) 

In [56]:
model_skipgram = gensim.models.Word2Vec(word_token, min_count=1, vector_size=100, window=5, sg=1)
vocabulary_skipgram = model_skipgram.wv.key_to_index
print(vocabulary_skipgram)


{'indonesia': 0, 'prabowo': 1, 'gibran': 2, 'pilih': 3, 'entertainment': 4, 'blackpink': 5, 'yg': 6, 'masyarakat': 7, 'milik': 8, 'presiden': 9, 'milu': 10, 'olahraga': 11, 'orang': 12, 'to': 13, 'juta': 14, 'anak': 15, 'scroll': 16, 'content': 17, 'kontrak': 18, 'sebut': 19, 'calon': 20, 'sport': 21, 'rp': 22, 'partai': 23, 'dukung': 24, 'salah': 25, 'lisa': 26, 'korea': 27, 'bisnis': 28, 'raffi': 29, 'jakarta': 30, 'motor': 31, 'dunia': 32, 'muda': 33, 'saham': 34, 'hasil': 35, 'lapor': 36, 'selatan': 37, 'grup': 38, 'k': 39, 'jumat': 40, 'temu': 41, 'kali': 42, 'anggota': 43, 'tingkat': 44, 'nagita': 45, 'konser': 46, 'saudi': 47, 'kota': 48, 'politik': 49, 'pop': 50, 'usia': 51, 'media': 52, 'turut': 53, 'pasang': 54, 'selenggara': 55, 'nama': 56, 'ketua': 57, 'subianto': 58, 'wakil': 59, 'debut': 60, 'tim': 61, 'main': 62, 'negara': 63, 'hadir': 64, 'buka': 65, 'jalan': 66, 'suara': 67, 'harga': 68, 'turun': 69, 'lagu': 70, 'with': 71, 'cawapres': 72, 'continue': 73, 'latih': 74, 

In [55]:
# Accessing the vocabulary for the skip-gram model
vocabulary_skipgram = model_skipgram.wv.key_to_index
print(vocabulary_skipgram)


{'indonesia': 0, 'prabowo': 1, 'gibran': 2, 'pilih': 3, 'entertainment': 4, 'blackpink': 5, 'yg': 6, 'masyarakat': 7, 'milik': 8, 'presiden': 9, 'milu': 10, 'olahraga': 11, 'orang': 12, 'to': 13, 'juta': 14, 'anak': 15, 'scroll': 16, 'content': 17, 'kontrak': 18, 'sebut': 19, 'calon': 20, 'sport': 21, 'rp': 22, 'partai': 23, 'dukung': 24, 'salah': 25, 'lisa': 26, 'korea': 27, 'bisnis': 28, 'raffi': 29, 'jakarta': 30, 'motor': 31, 'dunia': 32, 'muda': 33, 'saham': 34, 'hasil': 35, 'lapor': 36, 'selatan': 37, 'grup': 38, 'k': 39, 'jumat': 40, 'temu': 41, 'kali': 42, 'anggota': 43, 'tingkat': 44, 'nagita': 45, 'konser': 46, 'saudi': 47, 'kota': 48, 'politik': 49, 'pop': 50, 'usia': 51, 'media': 52, 'turut': 53, 'pasang': 54, 'selenggara': 55, 'nama': 56, 'ketua': 57, 'subianto': 58, 'wakil': 59, 'debut': 60, 'tim': 61, 'main': 62, 'negara': 63, 'hadir': 64, 'buka': 65, 'jalan': 66, 'suara': 67, 'harga': 68, 'turun': 69, 'lagu': 70, 'with': 71, 'cawapres': 72, 'continue': 73, 'latih': 74, 

In [57]:
print(model_skipgram.wv.similarity('politik','pdip'))

0.9983548


In [58]:
print(model_skipgram.wv.similarity('saham','politik'))

0.9852162


In [59]:
similar_words = model_skipgram.wv.most_similar("cawapres")
print(similar_words)

[('wakil', 0.9972952604293823), ('capres', 0.9966903924942017), ('pasang', 0.9966230392456055), ('raka', 0.9964179396629333), ('calon', 0.9963775873184204), ('prabowo', 0.9963279366493225), ('subianto', 0.9960774183273315), ('pilpres', 0.9958113431930542), ('kiri', 0.9953056573867798), ('rakabuming', 0.9952070713043213)]


In [60]:
vectors_skipgram = [model_skipgram.wv.get_vector(word)for word in vocabulary_skipgram]

In [61]:
vectors_skipgram[0]

array([-2.88131475e-01,  2.95679897e-01,  8.57135728e-02,  5.51410988e-02,
       -3.86452787e-02, -3.36000264e-01,  2.16062725e-01,  3.91588271e-01,
       -2.31562749e-01, -5.26964553e-02, -2.91153669e-01, -2.47742072e-01,
       -1.04332843e-03,  1.65278599e-01,  1.66739181e-01, -1.68188870e-01,
        2.76356377e-02, -2.84534395e-01, -1.09783541e-02, -3.86020750e-01,
        1.51601836e-01,  2.09975734e-01,  7.87223652e-02,  2.82460414e-02,
       -1.00753196e-02, -4.90266569e-02, -1.08637661e-01, -5.74068353e-02,
       -3.38909268e-01,  3.79089974e-02,  2.23142549e-01, -2.98080198e-03,
       -8.33368748e-02, -3.74545753e-02, -9.54822525e-02,  2.21302539e-01,
        6.74673840e-02, -2.64543325e-01, -9.22504514e-02, -3.19618464e-01,
       -1.28026932e-01, -1.53644666e-01, -7.79179391e-04, -2.91391239e-02,
        2.33064413e-01, -4.94275317e-02, -2.88401783e-01,  1.14608049e-01,
        1.04258515e-01,  1.70384169e-01,  5.82205653e-02, -8.58709142e-02,
       -1.34816930e-01, -

**Word2Vec Glove**


In [62]:
import gensim.downloader as api

In [63]:
from gensim.models import KeyedVectors

In [65]:
#pretrain model
model_glove = api.load("glove-twitter-25")

In [66]:
model_glove.most_similar(positive=['cawapres'], topn=2)

[('timses', 0.8903828263282776), ('menpora', 0.8787609934806824)]

In [67]:
# Accessing the vocabulary for the GloVe model
vocabulary_glove = model_glove.key_to_index


In [68]:
# Retrieve word vectors for words in the vocabulary for the GloVe model
vector_glove = [model_glove.get_vector(word) for word in vocabulary_glove]


In [69]:
vector_glove[0]

array([ 0.62415 ,  0.62476 , -0.082335,  0.20101 , -0.13741 , -0.11431 ,
        0.77909 ,  2.6356  , -0.46351 ,  0.57465 , -0.024888, -0.015466,
       -2.9696  , -0.49876 ,  0.095034, -0.94879 , -0.017336, -0.86349 ,
       -1.3348  ,  0.046811,  0.36999 , -0.57663 , -0.48469 ,  0.40078 ,
        0.75345 ], dtype=float32)

**Fasttext**

In [70]:
meta_hyper = {
    "vector_size": 4, # size of embedding 
    "alpha": 0.025, # learning rate
    "window": 5,
    "min_freq" : 1,
    "epochs": 3, # number of training epochs
    "vocab_size": 20, #len(set([td for td in word_token])), #size of vocabulary
    "data_description": "Add your description here",
    "data_size": len(word_token),
    "tokens_number": len([td for td in word_token]),
    "CPU": 8
}

In [71]:
from gensim.models import FastText

embed_model = FastText(vector_size=meta_hyper['vector_size'], 
                       window=meta_hyper['window'], 
                       min_count = meta_hyper['min_freq'], 
                       alpha= meta_hyper['alpha'], 
                       workers=meta_hyper['CPU'])

embed_model.build_vocab(word_token)

In [72]:
embed_model.train(word_token, total_examples=len(word_token), epochs=2)

(33061, 33890)

In [73]:
vector = embed_model.wv['cawapres']

In [74]:
vector

array([-0.03862438,  0.01652549,  0.08612684,  0.06033094], dtype=float32)

**Word2Vec Glove**


In [199]:
import gensim
from gensim.models import Word2Vec

In [200]:
model_cbow = gensim.models.Word2Vec(word_token, min_count=3, vector_size=50, window=5, sg=0)

In [201]:
# Accessing the vocabulary
vocabulary_cbow = model_cbow.wv.key_to_index
print(vocabulary_cbow)

# Accessing word vectors
word_vectors = model_cbow.wv.key_to_index

{'indonesia': 0, 'prabowo': 1, 'gibran': 2, 'pilih': 3, 'entertainment': 4, 'blackpink': 5, 'yg': 6, 'masyarakat': 7, 'presiden': 8, 'milik': 9, 'milu': 10, 'olahraga': 11, 'orang': 12, 'to': 13, 'juta': 14, 'anak': 15, 'content': 16, 'scroll': 17, 'kontrak': 18, 'sebut': 19, 'calon': 20, 'sport': 21, 'rp': 22, 'partai': 23, 'salah': 24, 'dukung': 25, 'bisnis': 26, 'lisa': 27, 'korea': 28, 'jakarta': 29, 'raffi': 30, 'dunia': 31, 'muda': 32, 'motor': 33, 'hasil': 34, 'saham': 35, 'grup': 36, 'selatan': 37, 'lapor': 38, 'k': 39, 'temu': 40, 'jumat': 41, 'kali': 42, 'anggota': 43, 'tingkat': 44, 'saudi': 45, 'konser': 46, 'nagita': 47, 'pop': 48, 'politik': 49, 'kota': 50, 'turut': 51, 'usia': 52, 'media': 53, 'ketua': 54, 'nama': 55, 'pasang': 56, 'selenggara': 57, 'wakil': 58, 'subianto': 59, 'debut': 60, 'hadir': 61, 'negara': 62, 'main': 63, 'tim': 64, 'suara': 65, 'turun': 66, 'jalan': 67, 'harga': 68, 'lagu': 69, 'buka': 70, 'besar': 71, 'cawapres': 72, 'with': 73, 'latih': 74, 'co

In [202]:
#ini yang oke
vocabulary_cbow = model_cbow.wv.index_to_key
print(vocabulary_cbow)


['indonesia', 'prabowo', 'gibran', 'pilih', 'entertainment', 'blackpink', 'yg', 'masyarakat', 'presiden', 'milik', 'milu', 'olahraga', 'orang', 'to', 'juta', 'anak', 'content', 'scroll', 'kontrak', 'sebut', 'calon', 'sport', 'rp', 'partai', 'salah', 'dukung', 'bisnis', 'lisa', 'korea', 'jakarta', 'raffi', 'dunia', 'muda', 'motor', 'hasil', 'saham', 'grup', 'selatan', 'lapor', 'k', 'temu', 'jumat', 'kali', 'anggota', 'tingkat', 'saudi', 'konser', 'nagita', 'pop', 'politik', 'kota', 'turut', 'usia', 'media', 'ketua', 'nama', 'pasang', 'selenggara', 'wakil', 'subianto', 'debut', 'hadir', 'negara', 'main', 'tim', 'suara', 'turun', 'jalan', 'harga', 'lagu', 'buka', 'besar', 'cawapres', 'with', 'latih', 'continue', 'acara', 'klub', 'persen', 'kutip', 'tourism', 'jokowi', 'dasar', 'rakabuming', 'kait', 'raka', 'giat', 'kenal', 'utama', 'resmi', 'kpu', 'miliar', 'tonton', 'harap', 'jual', 'aku', 'hibur', 'masuk', 'tawar', 'putus', 'pimpin', 'resume', 'sukses', 'baru', 'pada', 'liga', 'advertis

In [203]:
#get the vector
vectors_cbow = [model_cbow.wv.get_vector(word)for word in vocabulary_cbow]

In [204]:
vectors_cbow[0]

array([ 0.00190297, -0.0374207 ,  0.03586261,  0.02083243, -0.11217009,
       -0.13196382,  0.13318764,  0.19635734, -0.21567772, -0.03319914,
       -0.00965453, -0.16269149, -0.04286444,  0.05324448, -0.1399634 ,
        0.05698736,  0.09785727, -0.0534799 , -0.1779642 , -0.13283153,
        0.03834471,  0.09560016,  0.14680773, -0.09231891,  0.07272862,
       -0.0015295 , -0.09171021, -0.10895804, -0.15770078,  0.0452046 ,
        0.06443001,  0.01652089, -0.08375776,  0.01106556, -0.10335352,
        0.18683897,  0.02039961,  0.01048425,  0.04163299, -0.19711877,
        0.09823103, -0.04092675, -0.02597006,  0.03909997,  0.29617226,
        0.06443509, -0.02158078, -0.14370902,  0.07799406,  0.08529428],
      dtype=float32)

In [78]:
import numpy as np

def document_vector(word_vectors, doc):
    # Get word vectors for words in the document
    doc_vectors = [word_vectors[word] for word in doc if word in word_vectors]

    # Return the average vector for the document
    return np.mean(doc_vectors, axis=0)

# Example: Convert a list of documents to vectors
document_vectors = [document_vector(model_cbow.wv, doc) for doc in word_token]


In [79]:
#spliting data
from sklearn.model_selection import train_test_split

#X_train, X_test, y_train, y_test = train_test_split(document_vectors, Label, test_size=0.2, random_state=42)
X_train, X_test, y_train, y_test = train_test_split(document_vectors, Label, test_size=0.3, random_state=50)


#spliting data
#from sklearn.model_selection import train_test_split
#X_train, X_test, y_train, y_test= train_test_split(document_vectors['Label', test_size=0.2, random_state=42])


In [80]:
from sklearn.ensemble import RandomForestClassifier

# Initialize the model
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the model
rf_model.fit(X_train, y_train)

# Predict on the test set
rf_predictions = rf_model.predict(X_test)


**CBOW**

**Pemodelan RandomForest vs SVM**

In [81]:
from sklearn.metrics import accuracy_score, classification_report

# Evaluate accuracy
accuracy = accuracy_score(y_test, rf_predictions)
print(f"Random Forest Accuracy: {accuracy:.2f}")

# Display classification report
print("Classification Report:")
print(classification_report(y_test, rf_predictions))


Random Forest Accuracy: 0.63
Classification Report:
              precision    recall  f1-score   support

     Hiburan       0.62      0.42      0.50        12
    Olahraga       0.73      0.80      0.76        10
     Politik       0.50      0.80      0.62         5

    accuracy                           0.63        27
   macro avg       0.62      0.67      0.63        27
weighted avg       0.64      0.63      0.62        27



In [82]:
from sklearn.svm import SVC

# Initialize the model
svm_model = SVC(kernel='linear', C=1.0, random_state=42)

# Train the model
svm_model.fit(X_train, y_train)

# Predict on the test set
svm_predictions = svm_model.predict(X_test)


In [83]:
# Evaluate accuracy
accuracy_svm = accuracy_score(y_test, svm_predictions)
print(f"SVM Accuracy: {accuracy_svm:.2f}")

# Display classification report
print("SVM Classification Report:")
print(classification_report(y_test, svm_predictions))


SVM Accuracy: 0.19
SVM Classification Report:
              precision    recall  f1-score   support

     Hiburan       0.00      0.00      0.00        12
    Olahraga       0.00      0.00      0.00        10
     Politik       0.19      1.00      0.31         5

    accuracy                           0.19        27
   macro avg       0.06      0.33      0.10        27
weighted avg       0.03      0.19      0.06        27



c:\Users\Lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(avera

***SVM***

In [84]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report

# Initialize the SVM model with a polynomial kernel
svm_model_poly = SVC(kernel='poly', degree=3, C=1.0, random_state=42)

# Train the model
svm_model_poly.fit(X_train, y_train)

# Predict on the test set
svm_predictions_poly = svm_model_poly.predict(X_test)

# Evaluate accuracy
accuracy_poly = accuracy_score(y_test, svm_predictions_poly)
print(f"SVM with Polynomial Kernel (Degree 3) Accuracy: {accuracy_poly:.2f}")

# Display classification report
print("Classification Report:")
print(classification_report(y_test, svm_predictions_poly))



SVM with Polynomial Kernel (Degree 3) Accuracy: 0.37
Classification Report:
              precision    recall  f1-score   support

     Hiburan       0.30      0.25      0.27        12
    Olahraga       0.60      0.30      0.40        10
     Politik       0.33      0.80      0.47         5

    accuracy                           0.37        27
   macro avg       0.41      0.45      0.38        27
weighted avg       0.42      0.37      0.36        27



**TFIDF**

In [18]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(TFIDF, Label, test_size=0.2, random_state=42)

# Random Forest Model
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)
rf_predictions = rf_model.predict(X_test)

# Evaluate Random Forest
rf_accuracy = accuracy_score(y_test, rf_predictions)
print(f"Random Forest Accuracy: {rf_accuracy:.2f}")

print("Random Forest Classification Report:")
print(classification_report(y_test, rf_predictions))



Random Forest Accuracy: 0.83
Random Forest Classification Report:
              precision    recall  f1-score   support

     Hiburan       0.86      0.86      0.86         7
    Olahraga       0.71      0.83      0.77         6
     Politik       1.00      0.80      0.89         5

    accuracy                           0.83        18
   macro avg       0.86      0.83      0.84        18
weighted avg       0.85      0.83      0.84        18



In [17]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(TFIDF, Label, test_size=0.2, random_state=42)

# SVM Model with Polynomial Kernel (degree 3)
svm_model_poly = SVC(kernel='poly', degree=3, random_state=42)
svm_model_poly.fit(X_train, y_train)
svm_predictions_poly = svm_model_poly.predict(X_test)

# Evaluate SVM with Polynomial Kernel
svm_accuracy_poly = accuracy_score(y_test, svm_predictions_poly)
print(f"SVM with Polynomial Kernel (Degree 3) Accuracy: {svm_accuracy_poly:.2f}")

print("SVM with Polynomial Kernel (Degree 3) Classification Report:")
print(classification_report(y_test, svm_predictions_poly))


SVM with Polynomial Kernel (Degree 3) Accuracy: 0.67
SVM with Polynomial Kernel (Degree 3) Classification Report:
              precision    recall  f1-score   support

     Hiburan       1.00      0.43      0.60         7
    Olahraga       0.50      1.00      0.67         6
     Politik       1.00      0.60      0.75         5

    accuracy                           0.67        18
   macro avg       0.83      0.68      0.67        18
weighted avg       0.83      0.67      0.66        18

